cart/urls.py
from django.urls import path
from . import views
from cart.views import PlaceOrderView

urlpatterns = [
    path('', views.cart),
    # 加入购物车  分别为商品的id和数量
    path('add/<int:gid>/<int:count>/', views.add),
    # 修改购物车中商品的数量 分别为商品的id和数量
    path('edit/<int:gid>/<int:count>/', views.edit),
    # 删除购物车中的某个商品
    path('delete/<int:gid>/', views.delete),
    path('place_order/', PlaceOrderView.as_view()),
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# 这是要注意是中括号，不是花括号，否则路由+=会报错
urlpatterns = [
    path('admin/', admin.site.urls),
    # 搜索引擎
    path('search/', include('haystack.urls')),
    # 引入users模块路由
    path('users/', include('users.urls', namespace='users')),
    # 引入goods模块路由
    path('', include('goods.urls')),
    # 引入购物车路由
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:  # 配置静态文件路径
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, SiteView
from users import views

# 定义用户模块的路由

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('info/', views.info, name='info'),
    path('order/', views.order, name='order'),
    path('site/', SiteView.as_view(), name='site')
]

app_name = 'users'

orders/models.py
from django.db import models
from utils.models import BaseModel
from users.models import User, Address
from goods.models import Goods


# Create your models here.


class OrderInfo(BaseModel):
    """订单信息"""
    PAY_METHODS = {
        1: "货到付款",
        2: "支付宝",
    }

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "ALIPAY": 2
    }

    PAY_METHOD_CHOICES = (
        (1, "货到付款"),
        (2, "支付宝"),
        (3, "微信"),
        (4, "银行卡"),
    )

    ORDER_STATUS = {
        1: "待支付",
        2: "待发货",
        3: "待收货",
        4: "待评价",
        5: "已完成",
    }

    ORDER_STATUS_ENUM = {
        "UNPAID": 1,
        "UNSEND": 2,
        "UNRECEIVED": 3,
        "UNCOMMENT": 4,
        "FINISHED": 5
    }

    ORDER_STATUS_CHOICES = (
        (1, "待支付"),
        (2, "待发货"),
        (3, "待收货"),
        (4, "待评价"),
        (5, "已完成"),
    )

    order_id = models.CharField(max_length=64, primary_key=True, verbose_name="订单号")
    user = models.ForeignKey(User, verbose_name="下单用户", on_delete=models.CASCADE)
    address = models.ForeignKey(Address, verbose_name="收获地址", on_delete=models.CASCADE)
    total_count = models.IntegerField(default=1, verbose_name="商品总数")
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="商品总金额")
    trans_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="运费")
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=1, verbose_name="支付方式")
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name="订单状态")
    trade_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name="支付编号")

    class Meta:
        db_table = "df_order_info"
        verbose_name = "订单信息"
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    """订单商品"""
    order = models.ForeignKey(OrderInfo, verbose_name="订单", on_delete=models.CASCADE)
    sku = models.ForeignKey(Goods, verbose_name="订单商品", on_delete=models.CASCADE)
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="单价")
    comment = models.TextField(default="", verbose_name="评价信息")

    class Meta:
        db_table = "df_order_goods"
        verbose_name = "订单商品"
        verbose_name_plural = verbose_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from utils.models import BaseModel
from django.conf import settings
from itsdangerous import TimedJSONWebSignatureSerializer


# Create your models here.


class User(AbstractUser, BaseModel):
    """用户"""

    class Meta:
        db_table = 'df_users'
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def genrate_active_token(self):
        """生成激活令牌"""
        serializer = TimedJSONWebSignatureSerializer(settings.SECRET_KEY, 3600)
        token = serializer.dumps({"confirm": self.id})  # 返回bytes类型
        return token.decode()


class Address(BaseModel):
    user = models.ForeignKey("User", on_delete=models.CASCADE, verbose_name="所属用户")
    receiver_name = models.CharField(max_length=20, verbose_name="收件人")
    receiver_mobile = models.CharField(max_length=11, verbose_name="联系电话")
    detail_addr = models.CharField(max_length=256, verbose_name="详细地址")
    zip_code = models.CharField(max_length=6, verbose_name="邮政编码")

    class Meta:
        db_table = "df_address"
        verbose_name = "地址"
        verbose_name_plural = verbose_name

orders/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from .models import User, Address
from orders.models import OrderInfo
from goods.models import Goods
import re  # 用于验证邮箱
from django.db import IntegrityError
from django.contrib.auth import login
from django.contrib.auth.hashers import check_password
from django.http import HttpResponseRedirect
from users import user_decorator
from django.core.paginator import Paginator


class RegisterView(View):
    """类视图：处理注册"""

    @staticmethod
    def get(request):
        """处理GET请求，返回注册页面"""
        return render(request, 'users/register.html')

    @staticmethod
    def post(request):
        """处理POST请求，实现注册逻辑"""

        # 获取注册请求参数
        user_name = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')

        # 参数校验：缺少任意一个参数，就不要在继续执行
        if not all([user_name, password, email]):
            return redirect(reverse('users/register'))
        # 判断邮箱
        if not re.match(r"^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$", email):
            return render(request, 'users/register.html', {'errmsg': '邮箱格式不正确'})
        # 判断是否勾选协
        if allow != 'on':
            return render(request, 'users/register.html', {'errmsg': '没有勾选用户协议'})

        # 保存数据到数据库
        try:
            # 隐私信息需要加密，可以直接使用django提供的用户认证系统完成
            user = User.objects.create_user(user_name, email, password)
        except IntegrityError:
            return render(request, 'users/register.html', {'errmsg': '用户已注册'})

        # 手动的将用户认证系统默认的激活状态is_active设置成False,默认是True
        user.is_active = False
        # 保存数据到数据库
        user.save()
        return render(request, 'users/login.html')


class LoginView(View):
    """类视图：处理登陆"""

    @staticmethod
    def get(request):
        """处理GET请求，返回登陆页面"""
        return render(request, 'users/login.html')

    @staticmethod
    def post(request):
        """处理POST请求，实现登陆逻辑"""

        # 获取注册请求参数
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        jizhu = request.POST.get('jizhu', 0)  # 当jizhu有值时,即jizhu被勾选等于1时,返回的数据为1,否则get返回后面的0

        # 参数校验：缺少任意一个参数，就不要在继续执行
        if not all([username, password]):
            return redirect(reverse('users:login'))

        # 使用自带的auth验证用户（有bug）
        # user = authenticate(username=username, password=password)

        # 根据用户名查询对象
        user = User.objects.get(username=username)

        # 判断：如果未查到则说明用户名错误，如果查到则判断密码是否正确，如果密码正确，则返回用户中心
        if user is None:
            # 响应登录页面，提示用户名不存在
            context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': username, 'upwd': password}
            return render(request, 'users/login.html', context)

        # 验证密码是否正确
        pwd = user.password
        if check_password(password, pwd):
            url = request.COOKIES.get('url', '/')  # 获取登录之前进入的页面,如果没有,则进入首页
            red = HttpResponseRedirect(url)  # 用变量记住,方便设置cookie
            # 记住用户名
            if jizhu != 0:
                red.set_cookie('username', username)  # 设置cookie保存用户名
            else:
                red.set_cookie('username', '', max_age=-1)  # max_age指的是过期时间,当为-1时为立刻过期
            # 使用django的用户认证系统，在session中保存用户的登陆状态
            login(request, user)
            request.session['username'] = username
            request.session['user_id'] = user.id
            # 登陆成功，重定向到主页
            return red
        else:
            # 响应登录页面，提示密码错误
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': username, 'upwd': password}
            return render(request, 'users/login.html', context)


# 收货地址视图
class SiteView(View):
    """类视图，处理收货地址"""

    @staticmethod
    def get(request):
        uid = request.session['user_id']  # 获取用户id
        if uid is None:
            return HttpResponseRedirect('login/')
        addr = Address.objects.filter(user_id=uid)
        address = None
        if len(addr) >= 1:
            address = addr.first()
        context = {'address': address}

        return render(request, 'users/site.html', context)

    @staticmethod
    def post(request):
        uid = request.session['user_id']  # 获取用户id
        if uid is None:
            return HttpResponseRedirect('login/')
        addrs = Address.objects.filter(user_id=uid)
        # 接受参数
        receiver_name = request.POST.get('receiver_name')
        detail_addr = request.POST.get('detail_addr')
        zip_code = request.POST.get('zip_code')
        receiver_mobile = request.POST.get('receiver_mobile')

        # 保存数据到数据库
        try:
            # 如果有地址，则修改
            if len(addrs) >= 1:
                address = addrs.first()
            else:
                address = Address()

            address.receiver_name = receiver_name
            address.detail_addr = detail_addr
            address.zip_code = zip_code
            address.receiver_mobile = receiver_mobile
            address.user_id = uid
            address.save()

            return HttpResponseRedirect("/users/site/")
        except IntegrityError:
            return render(request, 'users/site.html', {'errmsg': '保存失败'})


def logout(request):
    request.session.flush()  # 清空session信息
    return redirect('index')


# 用户中心
@user_decorator.login
def info(request):
    # 用户基本信息
    user = User.objects.get(id=request.session['user_id'])
    # 最近浏览(没有数据支撑，直接去商品)
    goods_list = Goods.objects.all()[:5]
    context = {
        'user': user,
        'goods_list': goods_list
    }
    return render(request, 'users/info.html', context)


# 用户订单
@user_decorator.login
def order(request):
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    # 用户基本信息
    user = User.objects.get(id=request.session['user_id'])
    # 用户所有订单
    order_list = OrderInfo.objects.filter(user_id=user.id)
    paginator = Paginator(order_list, 2)
    orders = paginator.page(page)
    context = {
        'user': user,
        'orders': orders
    }
    return render(request, 'users/order.html', context)

templates/users/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }}-天天生鲜</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {%block head%}

    {%endblock head%}
</head>

<body>
{% block body %}

{% endblock body %}

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/users/info.html
{% extends 'users/main.html' %}

{%block head%}{%endblock head%}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/users/info/" class="active">· 个人信息</a></li>
				<li><a href="/users/order/">· 全部订单</a></li>
				<li><a href="/users/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            <div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
                    <ul class="user_info_list">
                        <li><span>用户名：</span>{{ user.username }}</li>
                        <li><span>联系邮箱：</span>{{ user.email }}</li>
                        <li><span>联系地址：</span>
                            {% for addr in user.address_set.all %}
                                {{ addr.detail_addr }}
                            {% endfor %}
                        </li>
                    </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for goods in goods_list %}
                        <li>
                            <a href="/{{goods.id}}/"><img src="/upload/{{goods.default_image}}/"></a>
                            <h4><a href="/{{goods.id}}/">{{goods.name}}</a></h4>
                            <div class="operate">
                                <span class="prize">{{goods.price}}</span>
                                <span class="unit">{{goods.price}}/{{goods.unit}}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
	</div>
{% endblock body %}

templates/users/login.html
{% extends 'users/base.html' %}

{% block head %}
  <script>
    $(function(){
      name_error=false;
      pwd_error=false;

      if ({{ error_name }} == 1){
          $('.user_error').html('用户名错误').show();
        }

      if ({{ error_pwd }} == 1){
          $('.pwd_error').html('密码错误').show();
        }

      $('.name_input').blur(function () {
          if($('.name_input').val().length == 0){
              $('.user_error').html('请填写用户名').show();
              name_error=false;
          }else {
              $('.user_error').hide();
              name_error=true;
          }
      });

      $('.pass_input').blur(function () {
         if($('.pass_input').val().length == 0){
             $('.pwd_error').html('请填写密码').show();
             pwd_error=false;
         }else {
             $('.user_error').hide();
             name_error=true;
         }
      });

    })
  </script>
{% endblock head %}

{% block body %}

	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/users/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
                            <input type="checkbox" name="jizhu" value='1' checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

templates/users/main.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }}-天天生鲜</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {%block head%}{%endblock head%}
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.username|default:'' != '' %}
                    <div class="login_btn fl">
                        <a>欢迎您:</a>
                        <a>{{request.session.username}}</a>
                        <span>|</span>
                        <a href="/users/logout/">注销</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/users/login/">登录</a>
                        <span>|</span>
                        <a href="/users/register/">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/users/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/cart/place_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<form class="search_con fr" action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
		</form>
	</div>
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/users/order.html
{% extends 'users/main.html' %}

{% load mytag %}

{%block head%}{%endblock head%}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/users/info/">· 个人信息</a></li>
				<li><a href="/users/order/" class="active">· 全部订单</a></li>
				<li><a href="/users/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for order in orders %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.create_time }}</li>
                        <li class="col02">订单号：{{ order.order_id }}</li>
                        <li class="col02 stress">{{ order.status|order_status }}</li>
                    </ul>

                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for g in order.ordergoods_set.all %}
                                        <ul class="order_goods_list clearfix">
                                            <li class="col01"><img src="/static/images/goods02.jpg"></li>
                                            <li class="col02">{{ g.sku.name }}<em>{{ g.price }}元/{{ g.sku.unit }}</em></li>
                                            <li class="col03">{{ g.count }}</li>
                                            <li class="col04">{{ g.price }}</li>
                                        </ul>
                                    {% endfor %}
                                </td>
                                <td width="15%">{{ order.total_amount }}元</td>
                                <td width="15%">{{ order.status|order_status }}</td>
                                <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                            </tr>
                        </tbody>
                    </table>
                {% endfor %}
				<div class="pagenation">
					<span class="step-links">
                    {% if orders.has_previous %}
                        <a href="?page={{ orders.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ orders.number }} of {{ orders.paginator.num_pages }}.
                    </span>

                    {% if orders.has_next %}
                        <a href="?page={{ orders.next_page_number }}">next</a>
                    {% endif %}
                </span>
				</div>
		</div>
	</div>

{% endblock body %}

templates/users/register.html
{% extends 'users/base.html' %}
{%block head%}
    <script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head%}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a href="/" class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="" method="post" id="zhuceform">
                    {% csrf_token %}
					<ul>
						<li>
							<label>用户名:</label>
							<input type="text" name="user_name" id="user_name">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>密码:</label>
							<input type="password" name="pwd" id="pwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>确认密码:</label>
							<input type="password" name="cpwd" id="cpwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>邮箱:</label>
							<input type="text" name="email" id="email">
							<span class="error_tip">提示信息</span>
						</li>
						<li class="agreement">
							<input type="checkbox" name="allow" id="allow" checked="checked">
							<label>同意”天天生鲜用户使用协议“</label>
							<span class="error_tip2">提示信息</span>
						</li>
						<li class="reg_sub">
							<input type="button" value="注 册" id="zhuce">
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock body %}

templates/users/site.html
{% extends 'users/main.html' %}

{%block head%}{%endblock head%}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/users/info/">· 个人信息</a></li>
				<li><a href="/users/order/">· 全部订单</a></li>
				<li><a href="/users/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>
                            {% if address %}
                                {{ address.detail_addr }}&nbsp;&nbsp;({{ address.receiver_name }})&nbsp;&nbsp;{{address.receiver_mobile}}
                            {% else %}
                                暂无收货地址
                            {% endif %}

                        </dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver_name" value="{{ address.receiver_name }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="detail_addr">{{address.detail_addr}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code" value="{{ address.zip_code }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="receiver_mobile" value="{{ address.receiver_mobile }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}